# Generated by Django 3.1.7 on 2021-02-28 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_remove_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detsale',
            name='prod',
        ),
        migrations.RemoveField(
            model_name='detsale',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cli',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='DetSale',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
